#'
#' This document reproduces tables and figures.
#'
#' The HTML output file was generated by
# library("knitr")
# spin("analysis.R")
#'
#' Check for packages and if necessary install into library 
#+ message = FALSE
rm(list=ls())
pkgs <- c("mgcv", "knitr", "multcomp", "coin", "colorspace", "ggplot2", 
          "data.table", "tidyverse", "vegan") 

inst <- pkgs %in% installed.packages()
if (any(inst)) install.packages(pkgs[!inst])
pkg_out <- lapply(pkgs, require, character.only = TRUE)
#' Results were obtained in this environment
date()
sessionInfo()
#' Load trapping counts
#' Cleaned and validated counts from Battles et al., 2024 
DE <- read.csv("DE.csv")
DE$X <- "DE"
NJ <- read.csv("NJ.csv")
NJ$X <- "NJ"
Full <- rbind(DE[, c(1,2,3,6,8,10)], NJ[, c(1,2,3,4,5,6)])
Full$count[Full$count == 0] <- 0.1
Full$location[Full$location == "Elm D."] <- "ElmD"
Full$location[Full$location == "Hammonton D-2"] <- "HammontonD2"
Full$location[Full$location == "Woodstown B"] <- "WoodstownB"
Full$location[Full$location == "East Vineland-1"] <- "EastVineland1"
Full$location[Full$location == "East Vineland-2"] <- "EastVineland2"
Full$location[Full$location == "Indian Mills J-2"] <- "IndianMillsJ2"
Full$location[Full$location == "Dayton V"] <- "DaytonV"
Full$location[Full$location == "Folsom E"] <- "FolsomE"
Full$location[Full$location == "Cedarville-1"] <- "Cedarville1"
Full$location[Full$location == "Chester D"] <- "ChesterD"
Full$location[Full$location == "South Branch"] <- "SouthBranch"
Full$location[Full$location == "Jones Island"] <- "JonesIsland"
Full$location[Full$location == "Rising Sun"] <- "RisingSun"
Full$location[Full$location == "New Egypt H"] <- "NewEgyptH"
Full$location[Full$location == "Green Creek"] <- "GreenCreek"
Full$locations <- paste(Full$X, Full$location, sep = "_")
Full <- Full[, -(1:2)]
Full$logcount <- log10(Full$count)

# Reomve four sites with only data from 2023 to 2024
Fullx <- Full[!Full$locations == "DE_Canterbury", ]
Fullx <- Fullx[!Fullx$locations == "DE_Woodenhawk", ]
Fullx <- Fullx[!Fullx$locations == "DE_Redden", ]
Fullx <- Fullx[!Fullx$locations == "NJ_Bellemeade", ]

write.csv(Fullx, "Full.csv")

colfunc <- colorRampPalette(c("blue", "yellow", "brown4"))

plot(1, type="n", xlab="", ylab="", xlim=c(min(Fullx$doy), max(Fullx$doy)), ylim=c(min(Fullx$logcount), max(Fullx$logcount)), xaxt="n")
axis(1, xaxp=c(130, 270, 14), las=2)
for (i in 1:27){
  with(Fullx[(Fullx$trap_type == "CEW Pheromone") & (Fullx$year == 1997+i),], points(doy, logcount, cex=0.7, pch=19, col=colfunc(27)[i]))
  with(Fullx[(Fullx$trap_type == "CEW BLT") & (Fullx$year == 1997+i),], points(doy, logcount, cex=0.7, pch=17, col=colfunc(27)[i]))
}

plot(1, type="n", xlab="", ylab="", xlim=c(min(Fullx$doy), max(Fullx$doy)), ylim=c(min(Fullx$logcount), max(Fullx$logcount)), xaxt="n")
axis(1, xaxp=c(130, 270, 14), las=2)
for (i in 1:27){
  with(Fullx[(Fullx$trap_type == "CEW Pheromone") & (Fullx$year == 1997+i),], lines(smooth.spline(logcount ~ doy), lwd=2, col=colfunc(27)[i]))
  with(Fullx[(Fullx$trap_type == "CEW BLT") & (Fullx$year == 1997+i),], lines(smooth.spline(logcount ~ doy), lwd=2, lty=3, col=colfunc(27)[i]))
}

Annual <- Fullx[, c(1,2,3,5)]
Annual$count[Annual$count == 0.1] <- 0

Annual$type <- paste(Annual$trap_type, Annual$locations, Annual$year, sep = "@")
Annual_mean <- aggregate(count ~ type, Annual, mean)

Annual_means <- Annual_mean %>%
  separate(col = type, into = c("type", "location", "year"), sep = "@")

Annual_means <- Annual_means %>%
  separate(col = location, into = c("state", "county"), sep = "_")

Annual_means$type[Annual_means$type == "CEW BLT"] <- "BLT"
Annual_means$type[Annual_means$type == "CEW Pheromone"] <- "Pheromone"
Annual_means$count[Annual_means$count == 0] <- 0.01 
Annual_means$cyear <- as.factor(Annual_means$year)

# Set colors for each line in data set
bo <- boxplot(count ~ cyear, 
              log = "y", xlab = "Year", ylab = "Counts/day", data = Annual_means, 
              axes = FALSE, col = rgb(0,0,1.0,alpha=0), border = rgb(0,0,1.0,alpha=0))

bo <- boxplot(count ~ cyear, 
              log = "y", xlab = "Year", ylab = "Counts/day", data = subset(Annual_means, type=="Pheromone" & state=="DE"), 
              axes = FALSE, col= rgb(0,0,1.0,alpha=0), border="orange", add=TRUE)

bo <- boxplot(count ~ cyear, 
              log = "y", xlab = "Year", ylab = "Counts/day", data = subset(Annual_means, type=="BLT" & state=="DE"), 
              axes = FALSE, col= rgb(0,0,1.0,alpha=0), border="blue", add=TRUE)

axis(2, at = c(0.01, 1, 10, 50, 100), las = 1)
axis(1, at = 1:nlevels(Annual_means$cyear), labels = levels(Annual_means$cyear), las = 3)

bo <- stripchart(count ~ cyear, 
              log = "y", xlab = "Year", ylab = "Counts/day", data = subset(Annual_means, type=="BLT" & state=="NJ"), pch=22, col="blue", vertical=TRUE, add=TRUE)

bo <- stripchart(count ~ cyear, 
                 log = "y", xlab = "Year", ylab = "Counts/day", data = subset(Annual_means, type=="Pheromone" & state=="NJ"), pch=24, col="orange", vertical=TRUE, add=TRUE)


# Store monthly data (mean) for modelling
Monthly <- Fullx[, -6]
Monthly$count[Monthly$count == 0.1] <- 0 
Monthly <- Monthly[-which(Monthly$doy>273), ] # deleted 98 observations in October, leave 30010 observations
Monthly$month <- Monthly$doy
Monthly$month[Monthly$month <= 151] <- "May"
Monthly$month[Monthly$month <= 181] <- "Jun"
Monthly$month[Monthly$month <= 212] <- "Jul"
Monthly$month[Monthly$month <= 243] <- "Aug"
Monthly$month[Monthly$month <= 273] <- "Sep"
Monthly$type <- paste(Monthly$trap_type, Monthly$locations, Monthly$year, Monthly$month, sep = "@")
Monthly_mean <- aggregate(count ~ type, Monthly, mean)
write.csv(Monthly_mean, "Monthly_mean.csv")
